runtime: python310
entrypoint: gunicorn -b :$PORT run:app

env: flex
service: greenmax

runtime_config:
  python_version: "3.10"

env_variables:
 

network:
  instance_tag: greenmax
  name: default

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: static
    secure: always
  
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
